# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout and stuff
        uses: actions/checkout@v2.3.1
      - name: use node.js v18 ok
        uses: actions/setup-node@v1
        with:
          version: '18.x'
      - name: setup ur pnpm stuff
        uses: pnpm/action-setup@v2
        with:
          version: '8.x.x'

      - name: install ur packages
        run: pnpm install --frozen-lockfile

      - name: build my stupid app.
        run: pnpm build && touch ./out/.nojekyll

      - name: pls depoly
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: out